package_assets:         on          # (on, off, always)
embed_images:           off          # (on, off, datauri)
javascript_compressor:  yui     # (yui, closure)

javascripts:
  common:
    - public/javascripts/jquery-1.3.2.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery.dataTables.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/application.js
  admin:
    - public/javascripts/editing.js

stylesheets:
  common:
    - public/stylesheets/reset-fonts-grids.css
    - public/stylesheets/base.css
    - public/stylesheets/main.css
    - public/stylesheets/boxes.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/smoothness/jquery-ui-1.7.1.custom.css
    - public/stylesheets/sort_table.css
  admin:
